#!bin/bash
blue='\033[34;1m'
green='\033[32;1m'
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
white='\033[37;1m'
yellow='\033[33;1m'
Tebal='\x1b[00m\033[041m'
clear

echo "•=====================================•"
echo " Author : RIZKI GANTENG                        "
echo "•=====================================•"
figlet RIZKI  | lolcat
echo '
[1], Prank
[2], Exit Tools
'
echo
read -p "Masukan Pilihan Anda : " pil
if [[ $pil == 1 ]]; then
read -p "Masukan No Target : " nomor
link="https://id.jagreward.com/member/verify-mobile/$nomor"
curl -s $link
else
echo 'Terimakasih Telah Memakai Tools GW YA OM'
exit
fi
echo
